development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  database: ebt_development
  socket: <%= ENV['MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  database: ebt_test
  socket: <%= ENV['MYSQL_SOCKET'] || '/tmp/mysql.sock' %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
